### PR TITLE
only for dnscheck.py

### PR DESCRIPTION
**Pull request by stillson**
Just pick up dnscheck.py if you can. the rest is in progress and probable doesn't work

### CODE REVIEW

**Comment by max-b** [comment]
The garden isn't currently in use, so I think I'm going to hold off on any merges at the moment. I'd be much happier being able to merge in the whole thing when you're ready.

**Comment by stillson** [comment]
That's fine. I think I just wanted to share the code :)

Chris

**Comment by max-b** [comment]
awesome - lookin good. I haven't had a chance to run it yet, but it's a lot cleaner...

**Comment by gobengo** [comment]
this is so old. Can we close it?

**Comment by jhpoelen** [comment]
@bennlich what do you think?

**Comment by bennlich** [comment]
Let's close. Too much trouble to figure out what it's about given very little explanation in the PR conversation itself. Also appears to be related to the captive portal / walled garden, which seem to be on nobody's Todo list atm.

**Pull request closed without merging**
